import { getAuth } from "@clerk/nextjs/server";
import axios from "axios";

export async function POST(req) {
    const { userId } = await getAuth(req);
    if (!userId) {
        return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401 });
    }

    const { files, repoName } = await req.json();
    const token = session.accessToken;

    try {
        // 1. Create Repository
        let repoResponse;
        try {
            repoResponse = await axios.post(
                "https://api.github.com/user/repos",
                {
                    name: repoName,
                    description: "Generated by Bhavable AI Builder",
                    auto_init: true,
                },
                {
                    headers: {
                        Authorization: `token ${token}`,
                        Accept: "application/vnd.github.v3+json",
                    },
                }
            );
        } catch (e) {
            // If repo already exists, we might want to use it or error
            if (e.response?.status === 422) {
                return new Response(JSON.stringify({ error: "Repository already exists" }), { status: 422 });
            }
            throw e;
        }

        const owner = repoResponse.data.owner.login;
        const repo = repoResponse.data.name;

        // 2. Upload Files (Sequentially for simplicity in this example)
        // Note: For a real production app, you'd use the git data API to do this in one commit.
        for (const [path, content] of Object.entries(files)) {
            const fileContent = typeof content === 'string' ? content : content.code;
            if (!fileContent) continue;

            const cleanPath = path.startsWith('/') ? path.slice(1) : path;
            
            await axios.put(
                `https://api.github.com/repos/${owner}/${repo}/contents/${cleanPath}`,
                {
                    message: `Add ${cleanPath}`,
                    content: Buffer.from(fileContent).toString("base64"),
                },
                {
                    headers: {
                        Authorization: `token ${token}`,
                        Accept: "application/vnd.github.v3+json",
                    },
                }
            );
        }

        return new Response(JSON.stringify({ url: repoResponse.data.html_url }), { status: 200 });
    } catch (error) {
        console.error("GitHub Deployment Error:", error.response?.data || error.message);
        return new Response(JSON.stringify({ error: error.response?.data?.message || "Failed to deploy to GitHub" }), { status: 500 });
    }
}
